In [3]:
# Check for GPU
!nvidia-smi -L

GPU 0: NVIDIA GeForce RTX 2070 Super with Max-Q Design (UUID: GPU-bf3c05f4-d285-42f9-9239-aae61d4ea191)


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [3]:
train = pd.read_csv("TRAINING_SET_FINAL.csv")
train

date     Id      open      high       low  \
0      2015-01-13 11:15:00+05:30     33  0.260655  0.258264  0.270536   
1      2015-01-13 11:30:00+05:30     34  0.259364  0.257929  0.269662   
2      2015-01-13 11:45:00+05:30     35  0.260014  0.259107  0.271068   
3      2015-01-13 12:00:00+05:30     36  0.261016  0.258817  0.271851   
4      2015-01-13 12:15:00+05:30     37  0.261278  0.259025  0.271392   
...                          ...    ...       ...       ...       ...   
25462  2019-02-28 10:30:00+05:30  25495  0.711045  0.711635  0.721231   
25463  2019-02-28 10:45:00+05:30  25496  0.712138  0.712070  0.720268   
25464  2019-02-28 11:00:00+05:30  25497  0.710287  0.710058  0.719988   
25465  2019-02-28 11:15:00+05:30  25498  0.709853  0.709922  0.719988   
25466  2019-02-28 11:30:00+05:30  25499  0.710359  0.710022  0.720232   

          close  day  week     SMA_7    SMA_14  ...  PSARr_0.02_0.2  \
0      0.261868   13     3  0.263339  0.261930  ...               0   
1      0.262588   13     3  0.263171  0.262111  ...               0   
2      0.263545   13     3  0.263218  0.262479  ...               0   
3      0.263819   13     3  0.263273  0.262923  ...               0   
4      0.263025   13     3  0.263065  0.263128  ...               0   
...         ...  ...   ...       ...       ...  ...             ...   
25462  0.718972   28     9  0.716356  0.715153  ...               0   
25463  0.717022   28     9  0.717192  0.715279  ...               0   
25464  0.716538   28     9  0.717063  0.715391  ...               0   
25465  0.717085   28     9  0.717277  0.715434  ...               0   
25466  0.717195   28     9  0.717317  0.715599  ...               0   

       AROOND_14  AROONU_14  AROONOSC_14  STOCHk_14_3_3  STOCHd_14_3_3  \
0       0.000000  42.857143    42.857143   -1763.647282   -1675.479655   
1       0.000000  35.714286    35.714286      -8.622299   -1153.427392   
2       7.142857  28.571429    21.428571      55.026650    -572.414310   
3       0.000000  21.428571    21.428571      57.978114      34.794155   
4       0.000000  14.285714    14.285714      59.958207      57.654324   
...          ...        ...          ...            ...            ...   
25462   0.000000  64.285714    64.285714     129.227651     113.482826   
25463   0.000000  57.142857    57.142857     134.556715     124.950021   
25464  28.571429  50.000000    21.428571     129.093591     130.959319   
25465  21.428571  42.857143    21.428571     115.100027     126.250111   
25466  14.285714  35.714286    21.428571     116.706949     120.300189   

       MACD_12_26_9  MACDh_12_26_9  MACDs_12_26_9  KAMA_10_2_30  
0          0.003290      -0.000246       0.003536      0.246675  
1          0.003118      -0.000334       0.003453      0.247075  
2          0.003025      -0.000342       0.003367      0.247542  
3          0.002939      -0.000343       0.003281      0.247627  
4          0.002774      -0.000406       0.003180      0.247873  
...             ...            ...            ...           ...  
25462     -0.000656       0.000894      -0.001550      0.714781  
25463     -0.000532       0.000815      -0.001346      0.714912  
25464     -0.000467       0.000704      -0.001170      0.714996  
25465     -0.000367       0.000643      -0.001010      0.715056  
25466     -0.000275       0.000587      -0.000863      0.715250  

[25467 rows x 31 columns]

In [2]:
train_target = pd.read_csv("train_target.csv")

In [3]:
train_target

Id  target
0          0       1
1          1       0
2          2       1
3          3       0
4          4       0
...      ...     ...
25495  25495       0
25496  25496       1
25497  25497       1
25498  25498       0
25499  25499       0

[25500 rows x 2 columns]

In [4]:
labels = train_target["target"].copy()

In [5]:
labels = labels.to_numpy()

In [6]:
labels = labels[32:]

In [7]:
labels

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [8]:
train_labels = pd.DataFrame(labels,columns = ["target"])

In [9]:
train_labels

target
0           1
1           1
2           1
3           0
4           0
...       ...
25463       0
25464       1
25465       1
25466       0
25467       0

[25468 rows x 1 columns]

# SPLITTING INTO TRAINING AND TESTING DATASETS

In [12]:
train["target"] = train_labels["target"] 
train.tail()

date     Id      open      high       low  \
25462  2019-02-28 10:30:00+05:30  25495  0.711045  0.711635  0.721231   
25463  2019-02-28 10:45:00+05:30  25496  0.712138  0.712070  0.720268   
25464  2019-02-28 11:00:00+05:30  25497  0.710287  0.710058  0.719988   
25465  2019-02-28 11:15:00+05:30  25498  0.709853  0.709922  0.719988   
25466  2019-02-28 11:30:00+05:30  25499  0.710359  0.710022  0.720232   

          close  day  week     SMA_7    SMA_14  ...  AROOND_14  AROONU_14  \
25462  0.718972   28     9  0.716356  0.715153  ...   0.000000  64.285714   
25463  0.717022   28     9  0.717192  0.715279  ...   0.000000  57.142857   
25464  0.716538   28     9  0.717063  0.715391  ...  28.571429  50.000000   
25465  0.717085   28     9  0.717277  0.715434  ...  21.428571  42.857143   
25466  0.717195   28     9  0.717317  0.715599  ...  14.285714  35.714286   

       AROONOSC_14  STOCHk_14_3_3  STOCHd_14_3_3  MACD_12_26_9  MACDh_12_26_9  \
25462    64.285714     129.227651     113.482826     -0.000656       0.000894   
25463    57.142857     134.556715     124.950021     -0.000532       0.000815   
25464    21.428571     129.093591     130.959319     -0.000467       0.000704   
25465    21.428571     115.100027     126.250111     -0.000367       0.000643   
25466    21.428571     116.706949     120.300189     -0.000275       0.000587   

       MACDs_12_26_9  KAMA_10_2_30  target  
25462      -0.001550      0.714781       0  
25463      -0.001346      0.714912       0  
25464      -0.001170      0.714996       1  
25465      -0.001010      0.715056       1  
25466      -0.000863      0.715250       0  

[5 rows x 32 columns]

In [13]:
from sklearn.model_selection import train_test_split
train_df,test_df = train_test_split(train,test_size=0.2,shuffle=False)
train_df.shape,test_df.shape

((20373, 32), (5094, 32))

In [14]:
train_df.drop(["Id","week"],axis=1,inplace=True)

In [15]:
train_df

date      open      high       low     close  day  \
0      2015-01-13 11:15:00+05:30  0.260655  0.258264  0.270536  0.261868   13   
1      2015-01-13 11:30:00+05:30  0.259364  0.257929  0.269662  0.262588   13   
2      2015-01-13 11:45:00+05:30  0.260014  0.259107  0.271068  0.263545   13   
3      2015-01-13 12:00:00+05:30  0.261016  0.258817  0.271851  0.263819   13   
4      2015-01-13 12:15:00+05:30  0.261278  0.259025  0.271392  0.263025   13   
...                          ...       ...       ...       ...       ...  ...   
20368  2018-05-04 13:00:00+05:30  0.673273  0.672072  0.682240  0.678601    4   
20369  2018-05-04 13:15:00+05:30  0.672163  0.673649  0.682276  0.680671    4   
20370  2018-05-04 13:30:00+05:30  0.674276  0.674329  0.683600  0.680707    4   
20371  2018-05-04 13:45:00+05:30  0.674330  0.674410  0.683996  0.681227    4   
20372  2018-05-04 14:00:00+05:30  0.674691  0.675561  0.682681  0.679713    4   

          SMA_7    SMA_14    SMA_21      RSI_7  ...   AROOND_14  AROONU_14  \
0      0.263339  0.261930  0.258588  53.492162  ...    0.000000  42.857143   
1      0.263171  0.262111  0.259153  58.304684  ...    0.000000  35.714286   
2      0.263218  0.262479  0.259741  64.069883  ...    7.142857  28.571429   
3      0.263273  0.262923  0.260324  65.652936  ...    0.000000  21.428571   
4      0.263065  0.263128  0.260913  57.135864  ...    0.000000  14.285714   
...         ...       ...       ...        ...  ...         ...        ...   
20368  0.680032  0.681577  0.684415  22.196814  ...  100.000000   0.000000   
20369  0.680159  0.681375  0.683733  42.785621  ...   92.857143   0.000000   
20370  0.680324  0.681179  0.683191  43.095194  ...   85.714286   7.142857   
20371  0.680414  0.681033  0.682609  47.791550  ...   78.571429   0.000000   
20372  0.680234  0.680819  0.682136  37.325220  ...   71.428571  21.428571   

       AROONOSC_14  STOCHk_14_3_3  STOCHd_14_3_3  MACD_12_26_9  MACDh_12_26_9  \
0        42.857143   -1763.647282   -1675.479655      0.003290      -0.000246   
1        35.714286      -8.622299   -1153.427392      0.003118      -0.000334   
2        21.428571      55.026650    -572.414310      0.003025      -0.000342   
3        21.428571      57.978114      34.794155      0.002939      -0.000343   
4        14.285714      59.958207      57.654324      0.002774      -0.000406   
...            ...            ...            ...           ...            ...   
20368  -100.000000      61.074743      12.999437     -0.003030      -0.000169   
20369   -92.857143      84.167510      54.442974     -0.002876      -0.000012   
20370   -78.571429      50.980438      65.407564     -0.002720       0.000115   
20371   -78.571429      26.650238      53.932729     -0.002525       0.000248   
20372   -50.000000      31.647070      36.425916     -0.002465       0.000247   

       MACDs_12_26_9  KAMA_10_2_30  target  
0           0.003536      0.246675       1  
1           0.003453      0.247075       1  
2           0.003367      0.247542       1  
3           0.003281      0.247627       0  
4           0.003180      0.247873       0  
...              ...           ...     ...  
20368      -0.002861      0.681030       1  
20369      -0.002864      0.681020       1  
20370      -0.002835      0.681003       1  
20371      -0.002773      0.681009       0  
20372      -0.002712      0.681003       0  

[20373 rows x 30 columns]

In [16]:
test_df.drop(["Id","week"],axis=1,inplace=True)

# STANDARDIZING THE DATA

In [47]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()

In [48]:
values = train_df.drop(["date","target"],axis=1)

In [49]:
standard_scaler.fit(values)

StandardScaler()

In [50]:
values = standard_scaler.transform(values)

In [51]:
values

array([[-0.53089122, -0.53622276, -0.53121092, ..., -0.28056776,
         1.16790542, -0.62370649],
       [-0.53823842, -0.53812442, -0.53619273, ..., -0.38152646,
         1.13908959, -0.6214498 ],
       [-0.53453913, -0.53144295, -0.52818075, ..., -0.39082265,
         1.10957424, -0.61881422],
       ...,
       [ 1.8225737 ,  1.82305502,  1.82410539, ...,  0.13346284,
        -1.02893818,  1.82627841],
       [ 1.82288198,  1.82351758,  1.82636519, ...,  0.28547491,
        -1.00756358,  1.82631595],
       [ 1.82493714,  1.83004486,  1.81886679, ...,  0.28421056,
        -0.98628412,  1.82628024]])

In [22]:
test_values = test_df.drop(["date","target"],axis=1)
test_values = test_values.values
standard_scaler.fit(test_values)
test_values = standard_scaler.transform(test_values)

In [23]:
labels = train_df["target"].to_numpy()

In [24]:
labels,len(labels)

(array([1, 1, 1, ..., 1, 0, 0], dtype=int64), 20373)

In [25]:
test_labels = test_df["target"].to_numpy()
test_labels,len(test_labels)

(array([0, 1, 0, ..., 1, 1, 0], dtype=int64), 5094)

In [26]:
#final training data:
labels.shape,values.shape

((20373,), (20373, 28))

# MODEL 1

In [72]:
#model1
tf.random.set_seed(42)
inputs = tf.keras.layers.Input(shape=28)
x = tf.keras.layers.Dense(10,activation="relu")(inputs)
x = tf.keras.layers.Lambda(lambda x:tf.expand_dims(x,axis=1))(x)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(1024,return_sequences=True))(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True)(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True)(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(10,activation="relu")(x)
outputs = tf.keras.layers.Dense(1,activation="sigmoid")(x)
model1 = tf.keras.models.Model(inputs,outputs)
model1.summary()

Model: "model_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_10 (InputLayer)       [(None, 28)]              0         
                                                                 
 dense_16 (Dense)            (None, 10)                290       
                                                                 
 lambda_9 (Lambda)           (None, 1, 10)             0         
                                                                 
 bidirectional (Bidirectiona  (None, 1, 2048)          8478720   
 l)                                                              
                                                                 
 lstm_23 (LSTM)              (None, 1, 1024)           12587008  
                                                                 
 lstm_24 (LSTM)              (None, 1, 1024)           8392704   
                                                           

In [73]:
model1.compile(loss = "binary_crossentropy",optimizer = tf.keras.optimizers.Adam(), metrics = "accuracy" )

In [74]:
history = model1.fit(values,
                     labels,
                     epochs=10,
                    batch_size=32)

Epoch 1/10
637/637 [==============================] - 14s 17ms/step - loss: 0.6938 - accuracy: 0.5097
Epoch 2/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6932 - accuracy: 0.5101
Epoch 3/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6930 - accuracy: 0.5108
Epoch 4/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6928 - accuracy: 0.5121
Epoch 5/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6931 - accuracy: 0.5126
Epoch 6/10
637/637 [==============================] - 11s 18ms/step - loss: 0.6929 - accuracy: 0.5136
Epoch 7/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6924 - accuracy: 0.5136
Epoch 8/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6924 - accuracy: 0.5163
Epoch 9/10
637/637 [==============================] - 11s 17ms/step - loss: 0.6923 - accuracy: 0.5155
Epoch 10/10
637/637 [==============================] - 11s 17ms/step - loss: 0.692

In [75]:
score = model1.evaluate(test_values,test_labels)
score

160/160 [==============================] - 2s 7ms/step - loss: 0.6936 - accuracy: 0.5035


[0.6935892105102539, 0.5035335421562195]

In [76]:
test = pd.read_csv("test_data.csv")

In [77]:
test

Id                       date      open      high       low  \
0          0  2019-02-28 11:45:00+05:30  0.603400  0.603456  0.601087   
1          1  2019-02-28 12:00:00+05:30  0.601100  0.602081  0.600225   
2          2  2019-02-28 12:15:00+05:30  0.600531  0.602038  0.600481   
3          3  2019-02-28 12:30:00+05:30  0.601025  0.601269  0.599850   
4          4  2019-02-28 12:45:00+05:30  0.601019  0.601263  0.599725   
...      ...                        ...       ...       ...       ...   
10312  10312  2020-11-02 13:45:00+05:30  0.702612  0.705156  0.702037   
10313  10313  2020-11-02 14:00:00+05:30  0.702838  0.708244  0.702400   
10314  10314  2020-11-02 14:15:00+05:30  0.706100  0.714519  0.706100   
10315  10315  2020-11-02 14:30:00+05:30  0.713413  0.715700  0.711888   
10316  10316  2020-11-02 14:45:00+05:30  0.714431  0.714463  0.711987   

          close  day  week     SMA_7    SMA_14    SMA_21      RSI_7  \
0      0.601100   28     9  0.603192  0.602410  0.601761  39.141180   
1      0.600575   28     9  0.602728  0.602515  0.601881  36.414816   
2      0.601019   28     9  0.602218  0.602506  0.602052  40.501595   
3      0.601019   28     9  0.601899  0.602633  0.602003  40.501595   
4      0.599800   28     9  0.601454  0.602366  0.601906  32.655532   
...         ...  ...   ...       ...       ...       ...        ...   
10312  0.702838    2    45  0.701772  0.702237  0.701807  57.562220   
10313  0.706200    2    45  0.702667  0.702475  0.701812  73.807565   
10314  0.713462    2    45  0.704557  0.703301  0.702177  86.667797   
10315  0.714519    2    45  0.706422  0.704122  0.702773  87.693093   
10316  0.713556    2    45  0.707992  0.704792  0.703446  81.065382   

          RSI_14     RSI_21    ATR_14   bb_mavg  bb_hband  bb_lband  
0      45.100563  46.593212  0.002758  0.601946  0.605627  0.598265  
1      43.896867  45.835237  0.002694  0.602103  0.605225  0.598982  
2      45.227509  46.606126  0.002613  0.602052  0.605209  0.598896  
3      45.227509  46.606126  0.002527  0.602011  0.605199  0.598823  
4      42.050687  44.680601  0.002457  0.601857  0.605157  0.598556  
...          ...        ...       ...       ...       ...       ...  
10312  51.643923  48.979101  0.003817  0.701593  0.706202  0.696984  
10313  59.775830  54.178170  0.003962  0.701613  0.706296  0.696929  
10314  71.085792  62.779617  0.004281  0.702185  0.709162  0.695208  
10315  72.305438  63.816847  0.004247  0.702940  0.711617  0.694263  
10316  69.431371  62.159456  0.004125  0.703805  0.713074  0.694537  

[10317 rows x 18 columns]

# PREPARING DATA FOR MODEL2

In [5]:
import pandas as pd
train = pd.read_csv("train_data.csv")
train.drop(["week","Id","date"],axis=1,inplace=True)
train

open      high       low     close  day     SMA_7    SMA_14  \
0      0.252483  0.249671  0.255665  0.250255   12  0.249131  0.246873   
1      0.247851  0.246028  0.257602  0.251258   12  0.250327  0.247607   
2      0.248817  0.248992  0.259178  0.253956   12  0.251520  0.248550   
3      0.251481  0.249916  0.260682  0.253628   12  0.252341  0.248788   
4      0.251066  0.250750  0.262421  0.255314   12  0.253037  0.249406   
...         ...       ...       ...       ...  ...       ...       ...   
25495  0.711045  0.711635  0.721231  0.718972   28  0.716356  0.715153   
25496  0.712138  0.712070  0.720268  0.717022   28  0.717192  0.715279   
25497  0.710287  0.710058  0.719988  0.716538   28  0.717063  0.715391   
25498  0.709853  0.709922  0.719988  0.717085   28  0.717277  0.715434   
25499  0.710359  0.710022  0.720232  0.717195   28  0.717317  0.715599   

         SMA_21      RSI_7     RSI_14     RSI_21    ATR_14   bb_mavg  \
0      0.247927  54.402627  48.236033  45.263488  0.007017  0.247667   
1      0.247838  57.307707  49.928940  46.453986  0.007040  0.247534   
2      0.247840  64.423555  54.263566  49.554022  0.007103  0.247566   
3      0.247855  62.935127  53.655190  49.190342  0.007076  0.247743   
4      0.248103  67.444567  56.362731  51.125779  0.007199  0.248086   
...         ...        ...        ...        ...       ...       ...   
25495  0.713530  61.663695  53.338774  51.661272  0.006446  0.713322   
25496  0.713498  53.363878  50.340798  49.789358  0.006478  0.713906   
25497  0.714031  51.366201  49.597282  49.324591  0.006513  0.714128   
25498  0.714268  53.657489  50.488807  49.880711  0.006520  0.714450   
25499  0.714580  54.161395  50.676715  49.995949  0.006559  0.714898   

       bb_hband  bb_lband  
0      0.256181  0.239153  
1      0.255730  0.239338  
2      0.255858  0.239275  
3      0.256385  0.239101  
4      0.257337  0.238835  
...         ...       ...  
25495  0.720650  0.705994  
25496  0.720413  0.707398  
25497  0.720676  0.707579  
25498  0.720914  0.707985  
25499  0.720792  0.709004  

[25500 rows x 15 columns]

In [6]:
values = train.values
values

array([[0.2524832 , 0.24967144, 0.25566544, ..., 0.24766699, 0.25618067,
        0.23915331],
       [0.2478509 , 0.24602779, 0.25760196, ..., 0.24753391, 0.25572977,
        0.23933805],
       [0.24881709, 0.24899165, 0.2591782 , ..., 0.24756627, 0.25585762,
        0.23927491],
       ...,
       [0.71028679, 0.7100581 , 0.71998847, ..., 0.7141275 , 0.72067604,
        0.70757896],
       [0.70985336, 0.70992214, 0.71998847, ..., 0.71444972, 0.72091398,
        0.70798546],
       [0.71035903, 0.71002184, 0.72023166, ..., 0.71489818, 0.72079233,
        0.70900404]])

In [7]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
s.fit(values)
values = s.transform(values)
values

array([[-0.8058208 , -0.81198957, -0.83730458, ..., -0.83856587,
        -0.83574818, -0.84082774],
       [-0.82729714, -0.82881621, -0.82830192, ..., -0.83917739,
        -0.83781824, -0.83997861],
       [-0.82281767, -0.81512887, -0.82097417, ..., -0.8390287 ,
        -0.83723126, -0.84026882],
       ...,
       [ 1.31665197,  1.31411156,  1.32128197, ...,  1.30487908,
         1.29671032,  1.31218737],
       [ 1.31464248,  1.3134837 ,  1.32128197, ...,  1.30635972,
         1.29780268,  1.31405575],
       [ 1.31698688,  1.31394413,  1.32241254, ...,  1.30842046,
         1.29724419,  1.31873742]])

In [12]:
target = pd.read_csv("train_target.csv")
target.drop(["Id"],axis = 1,inplace=True)
labels = target.values
labels = tf.squeeze(labels).numpy()
labels

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [14]:
values.shape,len(values)

((25500, 15), 25500)

In [15]:
from sklearn.model_selection import train_test_split
train,test,labels,test_labels = train_test_split(values,labels,test_size=0.2,shuffle=False)

In [20]:
tf.random.set_seed(42)
inputs = tf.keras.layers.Input(shape=15)
x = tf.keras.layers.Dense(10,activation="relu")(inputs)
x = tf.keras.layers.Lambda(lambda x:tf.expand_dims(x,axis=1))(x)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(1024,return_sequences=True))(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True)(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True)(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(10,activation="relu")(x)
outputs = tf.keras.layers.Dense(1,activation="sigmoid")(x)
model1 = tf.keras.models.Model(inputs,outputs)
model1.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 15)]              0         
                                                                 
 dense_3 (Dense)             (None, 10)                160       
                                                                 
 lambda_1 (Lambda)           (None, 1, 10)             0         
                                                                 
 bidirectional_1 (Bidirectio  (None, 1, 2048)          8478720   
 nal)                                                            
                                                                 
 lstm_4 (LSTM)               (None, 1, 1024)           12587008  
                                                                 
 lstm_5 (LSTM)               (None, 1, 1024)           8392704   
                                                           

In [23]:
model1.compile(loss = "binary_crossentropy",optimizer = tf.keras.optimizers.Adam(), metrics = "accuracy" )

In [73]:
history = model1.fit(train,
                     labels,
                     epochs=50,
                    batch_size=32)

Epoch 1/50
638/638 [==============================] - 12s 19ms/step - loss: 0.6919 - accuracy: 0.5216
Epoch 2/50
638/638 [==============================] - 12s 18ms/step - loss: 0.6920 - accuracy: 0.5219
Epoch 3/50
638/638 [==============================] - 12s 18ms/step - loss: 0.6917 - accuracy: 0.5209
Epoch 4/50
638/638 [==============================] - 11s 17ms/step - loss: 0.6918 - accuracy: 0.5190
Epoch 5/50
638/638 [==============================] - 10s 16ms/step - loss: 0.6917 - accuracy: 0.5235
Epoch 6/50
638/638 [==============================] - 10s 16ms/step - loss: 0.6917 - accuracy: 0.5246
Epoch 7/50
638/638 [==============================] - 10s 16ms/step - loss: 0.6917 - accuracy: 0.5205
Epoch 8/50
638/638 [==============================] - 10s 16ms/step - loss: 0.6920 - accuracy: 0.5190
Epoch 9/50
638/638 [==============================] - 10s 16ms/step - loss: 0.6916 - accuracy: 0.5238
Epoch 10/50
638/638 [==============================] - 10s 16ms/step - loss: 0.692

In [74]:
test = pd.read_csv("test_data.csv")
test.drop(["week","Id","date"],axis=1,inplace=True)
values = test.values
values

array([[0.6034    , 0.60345625, 0.6010875 , ..., 0.60194594, 0.60562733,
        0.59826455],
       [0.6011    , 0.60208125, 0.600225  , ..., 0.60210344, 0.60522458,
        0.59898229],
       [0.60053125, 0.6020375 , 0.60048125, ..., 0.6020525 , 0.60520933,
        0.59889567],
       ...,
       [0.7061    , 0.71451875, 0.7061    , ..., 0.70218531, 0.70916219,
        0.69520843],
       [0.7134125 , 0.7157    , 0.7118875 , ..., 0.70294031, 0.71161722,
        0.69426341],
       [0.71443125, 0.7144625 , 0.7119875 , ..., 0.70380531, 0.71307354,
        0.69453708]])

In [75]:
s.fit(values)
values = s.transform(values)
values

array([[-0.34844132, -0.36345368, -0.35066206, ..., -0.35978134,
        -0.42771608, -0.2952659 ],
       [-0.3673442 , -0.37481868, -0.35771096, ..., -0.35848433,
        -0.4311619 , -0.28959746],
       [-0.37201856, -0.3751803 , -0.35561672, ..., -0.35890379,
        -0.43129235, -0.29028161],
       ...,
       [ 0.49561377,  0.55452893,  0.50756606, ...,  0.46568975,
         0.45810483,  0.47035188],
       [ 0.55571263,  0.5642925 ,  0.55486515, ...,  0.47190718,
         0.47910949,  0.4628885 ],
       [ 0.56408538,  0.55406399,  0.55568241, ...,  0.47903045,
         0.49156947,  0.46504986]])

In [76]:
pred = model1.predict(values)

In [77]:
pred = tf.round(pred).numpy()

In [78]:
pred = tf.squeeze(pred).numpy()
pred = tf.cast(pred,dtype = tf.int64).numpy()
pred,pred.shape

(array([1, 1, 1, ..., 1, 1, 1], dtype=int64), (10317,))

In [79]:
l = np.arange(0,len(values))
l,l.shape

(array([    0,     1,     2, ..., 10314, 10315, 10316]), (10317,))

In [80]:
pred_df = pd.DataFrame(list(zip(l, pred)),
               columns =['Id', 'target'])
pred_df.to_csv("submission3.csv")

In [58]:
test

open      high       low     close  day     SMA_7    SMA_14  \
0      0.603400  0.603456  0.601087  0.601100   28  0.603192  0.602410   
1      0.601100  0.602081  0.600225  0.600575   28  0.602728  0.602515   
2      0.600531  0.602038  0.600481  0.601019   28  0.602218  0.602506   
3      0.601025  0.601269  0.599850  0.601019   28  0.601899  0.602633   
4      0.601019  0.601263  0.599725  0.599800   28  0.601454  0.602366   
...         ...       ...       ...       ...  ...       ...       ...   
10312  0.702612  0.705156  0.702037  0.702838    2  0.701772  0.702237   
10313  0.702838  0.708244  0.702400  0.706200    2  0.702667  0.702475   
10314  0.706100  0.714519  0.706100  0.713462    2  0.704557  0.703301   
10315  0.713413  0.715700  0.711888  0.714519    2  0.706422  0.704122   
10316  0.714431  0.714463  0.711987  0.713556    2  0.707992  0.704792   

         SMA_21      RSI_7     RSI_14     RSI_21    ATR_14   bb_mavg  \
0      0.601761  39.141180  45.100563  46.593212  0.002758  0.601946   
1      0.601881  36.414816  43.896867  45.835237  0.002694  0.602103   
2      0.602052  40.501595  45.227509  46.606126  0.002613  0.602052   
3      0.602003  40.501595  45.227509  46.606126  0.002527  0.602011   
4      0.601906  32.655532  42.050687  44.680601  0.002457  0.601857   
...         ...        ...        ...        ...       ...       ...   
10312  0.701807  57.562220  51.643923  48.979101  0.003817  0.701593   
10313  0.701812  73.807565  59.775830  54.178170  0.003962  0.701613   
10314  0.702177  86.667797  71.085792  62.779617  0.004281  0.702185   
10315  0.702773  87.693093  72.305438  63.816847  0.004247  0.702940   
10316  0.703446  81.065382  69.431371  62.159456  0.004125  0.703805   

       bb_hband  bb_lband  
0      0.605627  0.598265  
1      0.605225  0.598982  
2      0.605209  0.598896  
3      0.605199  0.598823  
4      0.605157  0.598556  
...         ...       ...  
10312  0.706202  0.696984  
10313  0.706296  0.696929  
10314  0.709162  0.695208  
10315  0.711617  0.694263  
10316  0.713074  0.694537  

[10317 rows x 15 columns]

array([[-0.8058208 , -0.81198957, -0.83730458, ..., -0.83856587,
        -0.83574818, -0.84082774],
       [-0.82729714, -0.82881621, -0.82830192, ..., -0.83917739,
        -0.83781824, -0.83997861],
       [-0.82281767, -0.81512887, -0.82097417, ..., -0.8390287 ,
        -0.83723126, -0.84026882],
       ...,
       [ 1.14463199,  1.14304066,  1.14972896, ...,  1.17838829,
         1.18672715,  1.169254  ],
       [ 1.14919519,  1.14915183,  1.15513056, ...,  1.17562388,
         1.18320826,  1.16724679],
       [ 1.15040925,  1.14902625,  1.15471183, ...,  1.17297674,
         1.17949467,  1.16566912]])

# BIDIRECTIONAL LSTMS MODEL2

In [81]:
tf.random.set_seed(42)
inputs = tf.keras.layers.Input(shape=15)
x = tf.keras.layers.Dense(27,activation="relu")(inputs)
x = tf.keras.layers.Lambda(lambda x:tf.expand_dims(x,axis=1))(x)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(1024,return_sequences=True))(x)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(1024,return_sequences=True))(x)
x = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(1024,return_sequences=True))(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(36,activation="relu")(x)
outputs = tf.keras.layers.Dense(1,activation="sigmoid")(x)
model2 = tf.keras.models.Model(inputs,outputs)
model2.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 15)]              0         
                                                                 
 dense_6 (Dense)             (None, 27)                432       
                                                                 
 lambda_2 (Lambda)           (None, 1, 27)             0         
                                                                 
 bidirectional_2 (Bidirectio  (None, 1, 2048)          8617984   
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 1, 2048)          25174016  
 nal)                                                            
                                                                 
 bidirectional_4 (Bidirectio  (None, 1, 2048)          2517

In [82]:
model2.compile(loss = "binary_crossentropy",optimizer = tf.keras.optimizers.Adam(), metrics = "accuracy" )

In [84]:
history2 = model2.fit(train,
                     labels,
                     epochs=50,
                    batch_size=32)

Epoch 1/50
638/638 [==============================] - 22s 29ms/step - loss: 0.6943 - accuracy: 0.5038
Epoch 2/50
638/638 [==============================] - 18s 29ms/step - loss: 0.6935 - accuracy: 0.5105
Epoch 3/50
638/638 [==============================] - 18s 29ms/step - loss: 0.6935 - accuracy: 0.5092
Epoch 4/50
638/638 [==============================] - 18s 29ms/step - loss: 0.6929 - accuracy: 0.5112
Epoch 5/50
638/638 [==============================] - 18s 29ms/step - loss: 0.6929 - accuracy: 0.5104
Epoch 6/50
638/638 [==============================] - 18s 29ms/step - loss: 0.6927 - accuracy: 0.5129
Epoch 7/50
638/638 [==============================] - 19s 29ms/step - loss: 0.6929 - accuracy: 0.5093
Epoch 8/50
638/638 [==============================] - 19s 29ms/step - loss: 0.6929 - accuracy: 0.5111
Epoch 9/50
638/638 [==============================] - 18s 29ms/step - loss: 0.6929 - accuracy: 0.5111
Epoch 10/50
638/638 [==============================] - 18s 29ms/step - loss: 0.692

KeyboardInterrupt: 

In [28]:
from tensorflow.keras.layers import LSTM,Dropout,Dense,Input 
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, CSVLogger
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras import optimizers
inputs = Input(shape=16)
x = Dense(20,activation="relu")(inputs)
x = tf.keras.layers.Lambda(lambda x:tf.expand_dims(x,axis=1))(x)
x = LSTM(25,return_sequences=False)(x)
x = Dropout(0.1)(x)
outputs = Dense(1,activation='sigmoid')(x)
model = Model(inputs=inputs, outputs=outputs)
model.compile(loss='binary_crossentropy',optimizer=optimizers.RMSprop(),
                      metrics=['accuracy'])

In [15]:
train = pd.read_csv("train_data.csv")
train.drop(["Id","date"],axis=1,inplace=True)
train = train.values
train.shape

(25500, 16)

In [16]:
target = pd.read_csv("train_target.csv")
labels = target["target"].to_numpy()
labels

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [29]:
history = model.fit(train,labels,epochs=20)

Epoch 1/20
797/797 [==============================] - 12s 6ms/step - loss: 0.6953 - accuracy: 0.5074
Epoch 2/20
797/797 [==============================] - 5s 6ms/step - loss: 0.6946 - accuracy: 0.5060
Epoch 3/20
797/797 [==============================] - 4s 6ms/step - loss: 0.6939 - accuracy: 0.5020
Epoch 4/20
797/797 [==============================] - 4s 5ms/step - loss: 0.6933 - accuracy: 0.5091
Epoch 5/20
797/797 [==============================] - 5s 6ms/step - loss: 0.6930 - accuracy: 0.5103
Epoch 6/20
797/797 [==============================] - 5s 6ms/step - loss: 0.6932 - accuracy: 0.5085
Epoch 7/20
797/797 [==============================] - 5s 6ms/step - loss: 0.6928 - accuracy: 0.5152
Epoch 8/20
797/797 [==============================] - 4s 5ms/step - loss: 0.6929 - accuracy: 0.5134
Epoch 9/20
797/797 [==============================] - 5s 6ms/step - loss: 0.6929 - accuracy: 0.5164
Epoch 10/20
797/797 [==============================] - 5s 6ms/step - loss: 0.6929 - accuracy: 0.511

In [41]:
# BiLSTM generator
in_gen = tf.keras.Input(shape=16)
x = Dense(20,activation="relu")(in_gen)
x = tf.keras.layers.Lambda(lambda x:tf.expand_dims(x,axis=1))(x)
lstm_1 = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64,return_sequences=False))(x)
dp_1 = tf.keras.layers.Dropout(0.1)(lstm_1)
bn_1 = tf.keras.layers.LayerNormalization()(dp_1)
rv_1 = tf.keras.layers.RepeatVector(1)(bn_1)
# BiLSTM generator output
gen_output = tf.keras.layers.Dense(1, activation='sigmoid')(rv_1)
alstm = tf.keras.models.Model(in_gen, gen_output) 

In [42]:
alstm.compile(loss="binary_crossentropy",optimizer = tf.keras.optimizers.Adam(),metrics = "accuracy")
alstm.fit(train,labels,epochs=20)

Epoch 1/20


ValueError: in user code:

    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\engine\training.py", line 809, in train_step
        loss = self.compiled_loss(
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\losses.py", line 1807, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "c:\users\harshvardhan bhosale\onedrive\desktop\stock market\venv1\lib\site-packages\keras\backend.py", line 5158, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((None, 1, 1) vs (None,)).


In [4]:
train = pd.read_csv("train_data.csv")
train.drop(["Id","date"],axis=1,inplace=True)
train = train.values
labels = pd.read_csv("train_target.csv")
labels = labels["target"].to_numpy()
train,labels

(array([[0.2524832 , 0.24967144, 0.25566544, ..., 0.24766699, 0.25618067,
         0.23915331],
        [0.2478509 , 0.24602779, 0.25760196, ..., 0.24753391, 0.25572977,
         0.23933805],
        [0.24881709, 0.24899165, 0.2591782 , ..., 0.24756627, 0.25585762,
         0.23927491],
        ...,
        [0.71028679, 0.7100581 , 0.71998847, ..., 0.7141275 , 0.72067604,
         0.70757896],
        [0.70985336, 0.70992214, 0.71998847, ..., 0.71444972, 0.72091398,
         0.70798546],
        [0.71035903, 0.71002184, 0.72023166, ..., 0.71489818, 0.72079233,
         0.70900404]]),
 array([1, 0, 1, ..., 1, 0, 0], dtype=int64))

In [6]:
inputs = tf.keras.layers.Input(shape=29)
x = tf.keras.layers.Dense(10,activation="relu")(inputs)
x = tf.keras.layers.Lambda(lambda x:tf.expand_dims(x,axis=1))(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True)(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True,dropout = 0.2)(x)
x = tf.keras.layers.LSTM(1024,return_sequences=True,dropout=0.1)(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(10,activation="relu")(x)
outputs = tf.keras.layers.Dense(1,activation="sigmoid")(x)
model1 = tf.keras.models.Model(inputs,outputs)
model1.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 29)]              0         
                                                                 
 dense (Dense)               (None, 10)                300       
                                                                 
 lambda (Lambda)             (None, 1, 10)             0         
                                                                 
 lstm (LSTM)                 (None, 1, 1024)           4239360   
                                                                 
 lstm_1 (LSTM)               (None, 1, 1024)           8392704   
                                                                 
 lstm_2 (LSTM)               (None, 1, 1024)           8392704   
                                                                 
 global_average_pooling1d (G  (None, 1024)             0     

In [7]:
model1.compile(loss = "binary_crossentropy", 
               optimizer = tf.keras.optimizers.Adam(learning_rate = 0.009),
               metrics = "accuracy")

In [17]:
history = model1.fit(train,labels,epochs = 20)

Epoch 1/20
797/797 [==============================] - 14s 14ms/step - loss: 0.6930 - accuracy: 0.5099
Epoch 2/20
797/797 [==============================] - 11s 14ms/step - loss: 0.6930 - accuracy: 0.5099
Epoch 3/20
797/797 [==============================] - 11s 14ms/step - loss: 0.6930 - accuracy: 0.5099
Epoch 4/20
797/797 [==============================] - 12s 14ms/step - loss: 0.6930 - accuracy: 0.5099
Epoch 5/20
117/797 [===>..........................] - ETA: 10s - loss: 0.6932 - accuracy: 0.5053

KeyboardInterrupt: 

In [18]:
train2 = pd.read_csv("TRAINING_SET_FINAL.csv")
train2

['date',
 'Id',
 'open',
 'high',
 'low',
 'close',
 'day',
 'week',
 'SMA_7',
 'SMA_14',
 'SMA_21',
 'RSI_7',
 'RSI_14',
 'RSI_21',
 'ATR_14',
 'bb_mavg',
 'bb_hband',
 'bb_lband',
 'PSARl_0.02_0.2',
 'PSARs_0.02_0.2',
 'PSARaf_0.02_0.2',
 'PSARr_0.02_0.2',
 'AROOND_14',
 'AROONU_14',
 'AROONOSC_14',
 'STOCHk_14_3_3',
 'STOCHd_14_3_3',
 'MACD_12_26_9',
 'MACDh_12_26_9',
 'MACDs_12_26_9',
 'KAMA_10_2_30']

In [3]:
train2 = pd.read_csv("TRAINING_SET_FINAL.csv")
train2.drop(["Id","date"],axis=1,inplace=True)
train2 = train2.values
labels = pd.read_csv("train_target.csv")
labels = labels["target"].to_numpy()
train2,labels

(array([[ 2.60655205e-01,  2.58263920e-01,  2.70536100e-01, ...,
         -2.46166935e-04,  3.53632935e-03,  2.46675093e-01],
        [ 2.59363938e-01,  2.57928559e-01,  2.69662415e-01, ...,
         -3.34301179e-04,  3.45275406e-03,  2.47075154e-01],
        [ 2.60014087e-01,  2.59106853e-01,  2.71067517e-01, ...,
         -3.42416502e-04,  3.36714993e-03,  2.47542383e-01],
        ...,
        [ 7.10286788e-01,  7.10058099e-01,  7.19988471e-01, ...,
          7.03757547e-04, -1.17039007e-03,  7.14996471e-01],
        [ 7.09853355e-01,  7.09922142e-01,  7.19988471e-01, ...,
          6.42967848e-04, -1.00964811e-03,  7.15056197e-01],
        [ 7.10359026e-01,  7.10021844e-01,  7.20231662e-01, ...,
          5.87345814e-04, -8.62811656e-04,  7.15250327e-01]]),
 array([1, 0, 1, ..., 1, 0, 0], dtype=int64))

In [4]:
from sklearn.preprocessing import MinMaxScaler
m = MinMaxScaler()
m.fit(train2)
train2 = m.transform(train2)
train2

array([[0.297067  , 0.29398898, 0.30530596, ..., 0.5059596 , 0.73372321,
        0.27207134],
       [0.29559535, 0.29360723, 0.30431998, ..., 0.49905426, 0.730624  ,
        0.2725296 ],
       [0.29633632, 0.29494852, 0.30590567, ..., 0.49841842, 0.72744956,
        0.27306481],
       ...,
       [0.80950911, 0.80827882, 0.81252287, ..., 0.58038636, 0.55918491,
        0.80852735],
       [0.80901513, 0.80812406, 0.81252287, ..., 0.57562347, 0.56514567,
        0.80859577],
       [0.80959144, 0.80823755, 0.81279732, ..., 0.57126548, 0.57059077,
        0.80881814]])

In [5]:
labels = labels[33:]
labels.shape,train2.shape

((25467,), (25467, 29))

In [ ]:
history = model1.fit(train2,labels,epochs = 20)

Epoch 1/20
796/796 [==============================] - 17s 13ms/step - loss: 0.6942 - accuracy: 0.5079
Epoch 2/20
796/796 [==============================] - 10s 12ms/step - loss: 0.6931 - accuracy: 0.5062
Epoch 3/20
796/796 [==============================] - 10s 12ms/step - loss: 0.6932 - accuracy: 0.5050
Epoch 4/20
796/796 [==============================] - 10s 13ms/step - loss: 0.6931 - accuracy: 0.5093
Epoch 5/20
796/796 [==============================] - 10s 13ms/step - loss: 0.6933 - accuracy: 0.5062
Epoch 6/20
796/796 [==============================] - 10s 13ms/step - loss: 0.6932 - accuracy: 0.5043
Epoch 7/20
796/796 [==============================] - 10s 13ms/step - loss: 0.6931 - accuracy: 0.5043
Epoch 8/20
796/796 [==============================] - 10s 13ms/step - loss: 0.6932 - accuracy: 0.5055
Epoch 9/20
796/796 [==============================] - 10s 13ms/step - loss: 0.6932 - accuracy: 0.5064
Epoch 10/20
796/796 [==============================] - 10s 13ms/step - loss: 0.693

In [31]:
from helperfuncs import plot_curves
plot_curves(history)

KeyError: 'val_loss'